### PR TITLE
New design

### PR DESCRIPTION
**Pull request by broccolini**
Had a go at re-designing the site. 

@jonmagic It needs tweaking with a real lesson in there and for registration (registration or full lesson info won't show locally). Either ping me on how to do that or see if you can work with my css. Also need email link for people who want to be mentors.

Content also needs reviewing - anyone can chip in on that if they have ideas, I just made a start. I put in a ying yang logo thing on there, not sure if we need that but it seems to kinda be the logo on the other sites, and that was the least bad version of it I could think of.

@kneath let me know if it's okay to use your photo in the banner. That one just works nicely :)

/cc @CoderDojoSF/mentors

### CODE REVIEW

**Comment by cameronmcefee** [comment]
Would it be possible to get a screenshot of the changes?

**Comment by broccolini** [comment]
Sure, here's 2 screenshots. As mentioned can't get the event to show locally so hasn't got all the info there. I figured made sense to have the next class up top and as every class is the same location to put that info there - need new GitHub address though!
screen shot 2013-10-21 at 10 21 10 am
screen shot 2013-10-21 at 10 16 38 am

**Comment by cameronmcefee** [comment]
:metal: Looks rad. It even has a good bit of the GitHub identity feel to it. Nice!

Address: 88 Colin P Kelly Jr Street, San Francisco, CA 94107

**Comment by broccolini** [comment]
Hehe I did have a look at some of the other hubber sites ;) I wondered if you wanted the GitHub logo or anything on there?

**Comment by cameronmcefee** [comment]
Yeah, we can definitely get it in there, but it doesn't need to be a huge thing.

How about "Hosted with <3 by GitHub" in the footer, ala http://boxen.github.com/

**Comment by KartikTalwar** [comment]
@broccolini looks awesome!

**Comment by broccolini** [comment]
@cameronmcefee yeah that looks good. Is that octocat somewhere I can grab?

**Comment by cameronmcefee** [comment]
http://cl.ly/0L2i3r2F290v

**Comment by jonmagic** [comment]
@broccolini this looks amazing! I'll work on getting you some seed data and make it easy to show/hide the registration form so you can finish the work around those things <3

**Comment by mikefowler** [comment]
@broccolini This is beautiful! Can't wait to see it working with lesson content.

**Comment by brntbeer** [comment]
:+1:

**Comment by broccolini** [comment]
@jonmagic that would be great, would be good to have a current and past lesson to work with. Was wondering if they lessons would just link to the repo or are you pulling the content into the site? 

I think having a full list of previous lesson on a separate page makes sense, but might need to consider how to group courses with lessons within them, and how it will look when there's a lot there. 

Do we already have a bunch of previous lessons we can add or are they not in the right format?

**Comment by mikefowler** [comment]
@jonmagic @brntbeer I'm going to put in some time on this over the weekend, finishing up the bits that @broccolini mentioned needed styles.

**Comment by jonmagic** [comment]
Sounds good.

**Pull request merged**
