### PR TITLE
ActiveAdmin interface

### PR DESCRIPTION
**Pull request by jonmagic**
I wired up [ActiveAdmin](http://www.activeadmin.info) for all of the models in the app and customized just enough to accomplish common tasks.

events coderdojosf__admin

/cc @CoderDojoSF/owners

### CODE REVIEW

**Comment by jonmagic** [comment]
Added lesson builder to active admin dashboard.

dashboard coderdojosf__admin

**Comment by brntbeer** [comment]
Guess im a little behind, I thought we created a lesson.json on the repos themselves?

**Comment by jonmagic** [comment]
@brntbeer this is just a handy generator, fill in the blanks and it gives you the json to save to lesson.json in the repository.

**Comment by brntbeer** [comment]
oh rad!

**Pull request merged**
