### PR TITLE
Farewell

### PR DESCRIPTION
**Pull request by cameronmcefee**
This adds a farewell notice to the home page and removes everything else.

cc @jonmagic @mikefowler for copy/deployment feedback.

cc @marcyDel since we're linking to CoderDojoSV

screen shot 2014-05-29 at 9 42 29 am

### CODE REVIEW

**Comment by jonmagic** [comment]
Does it still link to past lessons? Should it?

**Comment by cameronmcefee** [comment]
Yep, I left that part in.

**Comment by jonmagic** [comment]
:+1: from me then, I can deploy this this afternoon if you don’t have your machine already setup to.

**Comment by mikefowler** [comment]
:ship:

**Comment by cameronmcefee** [comment]
That would be swell @jonmagic

**Comment by kristjan** [comment]
:heart:

**Comment by skylar** [comment]
:beers:

**Comment by jonmagic** [comment]
:ship:

**Pull request merged**
