### PR TITLE
Design polish

### PR DESCRIPTION
**Pull request by jonmagic**
## Home page without upcoming event

01 home page without upcoming event
## Lesson with no event

02 lesson with no event
## Home page with upcoming event

03 home page with upcoming event
## Lesson with upcoming event

04 register to be notified
## You will be notified

05 you will be notified
## Event registration

06 event registration
## Please check your email to confirm registration

07 please check your email to confirm registration
## Registration confirmed

08 registration confirmed
## Registration failed

09 registration failed
## Registration closed

10 registration closed
## All lessons

11 lessons

### CODE REVIEW

**Comment by brntbeer** [comment]
stuff yeah!

**Comment by KartikTalwar** [comment]
Amazing!

**Comment by mikefowler** [comment]
Has this all been deployed, @jonmagic? Seeing some weirdness on the heroku instance (link underlining, newsletter form styles, responsive font sizes).

**Pull request merged**
